### ISSUE TITLE
Mejora el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-Nagema#1]
Buen trabajo @Nagema . !

Algunas pistas para acabarlo:

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen pero de forma que sea menos técnico, con un lenguaje más natural.
- [x] Añade un título a la página (Mi lista de Pokemons)
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Organiza los estilos (un archivo sass o css por componente)
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [ ] Elimina archivos sin usar y sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by Nagema** [comment]
hola @oneeyedman lo he terminado, avisame si falta algo por fa.
gracias :)

**Comment by oneeyedman** [comment]
Todo correcto salvo el último check, elimina el serviceworker y lo damos por hecho!

Buen trabajo.
